services:
  - type: web
    name: ResumeAnalyzer
    env: java
    branch: main
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/ResumeAnalyzer-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: PORT
        value: 10000
